export * from './term.interface';
export * from './legal.interface';
export * from './testimonial.interface';
export * from './service-item.interface';
export * from './partnership-item.interface';
export * from './faq-questions.interface';
export * from './menu-item.interface';
export * from './methodology-stage-item.interface';
export * from './response-mailchimp.interface';
